variable "twotproject" {}
variable "vpc_cidr" {}
variable "pubsub1_cidr" {}
variable "pubsub2_cidr" {}
variable "prisub1_cidr" {}
variable "prisub2_cidr" {}
variable "ami_id" {}
variable "instance_type" {}
variable "db_name" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "storage_type" {}
variable "identifier" {}
variable "db_username" {}
variable "db_password" {}
variable "parameter_group_name" {}
